### ISSUE TITLE
Add Account Enter your phone number to add account loading sending OTP

### ISSUE THREAD

**Issue by hoazgazh** [mxvsh/drivegram#4]
<img width="577" alt="image" src="https://github.com/user-attachments/assets/245943e9-c1ff-4f1e-99f8-4853d2eeb3eb">

as title, how can i debug this first step

**Comment by Jobians** [comment]
What exactly?

**Comment by mxvsh** [comment]
hi, @hoazgazh are you still there?

**Comment by Jobians** [comment]
Yes

**Comment by hoazgazh** [comment]
> hi, @hoazgazh are you still there?

Hi, i have resolved this issue,
I try to get inspect and find out my proxy cant route to some endpoint web because of my policy organization 🫥 

Switch to another ethernet to resolved this 😀

**Comment by Jobians** [comment]
@hoazgazh Alright
